#!/bin/sh


#S2E=/home/xqx/xqx/git/mygithub/s2e1.2/build/qemu-release/i386-softmmu/qemu-system-i386
S2E=/home/xqx/xqx/git/mygithub/s2e1.2/build/qemu-release/i386-s2e-softmmu/qemu-system-i386


gdb --args $S2E  -rtc clock=vm -net user -net nic,model=ne2k_pci -monitor telnet:localhost:4444,server,nowait  \
 /home/xqx/ubuntu9.04.raw -s -m 128     \
-s2e-config-file $1    \



